logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: DEBUG
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: Jeh96dits94$
        url: jdbc:mysql://localhost:3306/to-do-bulgaria?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

    #Init data
#    sql:
#        init:
#            mode: always

#Manager endpoints
management:
    endpoints:
        web:
#            base-path: "/admin"
            exposure:
                include: "*"

    endpoint:
        health:
          show-details: always

#Cloudinary Properties
cloudinary:
    api-key: '584545974723152'
    api-secret: f6oKiS1Wx6zAGb21iLSwt8Q1z4c
    cloud-Name: dabxnbbrp




